server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          password: thedamnP@1909
          search-paths: '{application}'
          uri: https://github.com/ChaitanyaMM/config.git
          username: ChaitanyaMM

logging:
  level:
    org:
      springframework:
        cloud: debug
        web: debug

